name: Build Android Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"

      - name: Build Release APK
        run: gradle assembleRelease

      - name: Build Release AAB
        run: gradle bundleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Gayan-Ganga-Release-APK
          path: app/build/outputs/apk/release/*.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: Gayan-Ganga-Release-AAB
          path: app/build/outputs/bundle/release/*.aab
